[package]
name = "MAIN"
version = "0.1.0"
edition = "2024"

[dependencies]
num_cpus = "1.14"
mio = "0.8"
libc = "0.2"
shared_memory = "0.12.4"
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3"
queues = "1.0.2"
http = "0.2"
httparse = "1.8"